<div class="container">
	<div class="row">
		<div class="col-12">
			<!-- Card START -->
			<div class="card border rounded-3">
				<!-- Card header START -->
				<div class="card-header border-bottom">
					<h3 class="mb-0">My Students List</h3>
				</div>
				<!-- Card header END -->

				<!-- Card body START -->
				<div class="card-body">
					<!-- Search and select START -->
					<div class="row g-3 align-items-center justify-content-between mb-4">
						<!-- Search -->
						<div class="col-md-8">
							<form class="rounded position-relative">
								<input id="search_student" class="form-control pe-5 bg-transparent" type="search" placeholder="Search" aria-label="Search">
								<button class="btn bg-transparent px-2 py-0 position-absolute top-50 end-0 translate-middle-y" type="submit"><i class="fas fa-search fs-6 "></i></button>
							</form>
						</div>

						<!-- Select option -->
						<div class="col-md-3">
							<!-- Short by filter -->
							<?php
							require_once "models/class.model.php";
							require_once "database/database.php";
							if (isset($_SESSION['class'])) {
								$classes = $_SESSION['class'];
							}
							
							?>
							<form>
								<select id="classFilter" class="form-select js-choice border-0 z-index-9 bg-transparent" aria-label=".form-select-sm">
									<option value="">All students</option>
									<?php foreach ($classes as $class) : ?>
										<?php if ($class['archive'] == 0) : ?>
											<option value="<?= $class['title'] ?>"><?= $class['title'] ?></option>
										<?php endif ?>
									<?php endforeach; ?>
								</select>
							</form>
						</div>
					</div>
				</div>



				<!-- Search and select END -->

				<!-- Student list table START -->
				<div class="table-responsive border-0">
					<table class="table table-dark-gray align-middle p-4 mb-0 table-hover">
						<!-- Table head -->
						<thead>
							<tr>
								<th scope="col" class="border-0 rounded-start">Student name</th>
								<th scope="col" class="border-0">Email</th>
								<th scope="col" class="border-0">Class</th>
								<th scope="col" class="border-0">Enrolled date</th>
								<th scope="col" class="border-0 rounded-end">Action</th>
							</tr>
						</thead>

						<!-- Table body START -->
						<script src="../../vendor/js/search_students.js"></script>
						<tbody>
							<!-- Table structure -->
							<div class="table-responsive">
								<table class="  table">
									<tbody id="studentTableBody">
										<!-- Table items go here as generated by PHP -->
										<?php foreach ($students as $student) :
											?>
											<tr>
												<!-- Table data -->
												<td>
													<div class="d-flex align-items-center position-relative">
														<!-- Image -->
														<div class="avatar avatar-md mb-2 mb-md-0">
															<img src="assets/images/profiles/<?= $student['image'] ?>" class="rounded" alt="">
														</div>
														<div class="mb-0 ms-2">
															<!-- Title -->
															<h6 class="mb-0"><a href="#" class="stretched-link"><?= $student['name'] ?></a></h6>
															<!-- Address -->
															<span class="text-body small"><i class="fas fa-fw fa-map-marker-alt me-1 mt-1"></i>Cambodia</span>
														</div>
													</div>
												</td>

												<!-- Table data -->
												<td class="text-center text-sm-start emaii"><?= $student['email'] ?></td>

												<!-- Table data -->
												<td><?= $student['title'] ?></td>

												<!-- Table data -->
												<td><?= $student['join_date'] ?></td>

												<!-- Table data -->
												<td>
													<a href="#" class="btn btn-success-soft btn-round me-1 mb-0" data-bs-toggle="tooltip" data-bs-placement="top" title="Message"><i class="far fa-envelope"></i></a>
													<button class="btn btn-danger-soft btn-round mb-0" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete"><i class="fas fa-trash"></i></button>
												</td>
											</tr>
										<?php endforeach; ?>
									</tbody>
								</table>
							</div>
							<!-- Student list table END -->

							<!-- Pagination START -->
							<div class="d-sm-flex justify-content-sm-between align-items-sm-center mt-4 mt-sm-3">
								<!-- Content -->
								<p class="mb-0 text-center text-sm-start">Showing 1 to 8 of 20 entries</p>
								<!-- Pagination -->
								<nav class="d-flex justify-content-center mb-0" aria-label="navigation">
									<ul class="pagination pagination-sm pagination-primary-soft mb-0 pb-0">
										<li class="page-item mb-0"><a class="page-link" href="#" tabindex="-1"><i class="fas fa-angle-left"></i></a></li>
										<li class="page-item mb-0"><a class="page-link" href="#">1</a></li>
										<li class="page-item mb-0 active"><a class="page-link" href="#">2</a></li>
										<li class="page-item mb-0"><a class="page-link" href="#">3</a></li>
										<li class="page-item mb-0"><a class="page-link" href="#"><i class="fas fa-angle-right"></i></a></li>
									</ul>
								</nav>
							</div>
				</div>
			</div>
		</div>
	</div>

</div>